### ISSUE TITLE
can't run reText 5.2

### ISSUE THREAD

**Issue by spectereye** [retext-project/retext#154]
hello!
i run reText 5.1 in windows 7 without problem, so just download the zip package and overwrite the files,  but find problem below, any ideas? thanks!
```bat
Using configuration file: \HKEY_CURRENT_USER\Software\ReText project\ReText
Traceback (most recent call last):
  File "retext.py", line 80, in <module>
    main()
  File "retext.py", line 60, in main
    window = ReTextWindow()
  File "c:\Program Files\ReText\ReText\window.py", line 61, in __init__
    QIcon.setThemeName(get_icon_theme())
  File "c:\Program Files\ReText\ReText\icontheme.py", line 47, in get_icon_theme
    return (get_from_xsettings()
  File "c:\Program Files\ReText\ReText\icontheme.py", line 20, in get_from_xsettings
    xsettings = get_xsettings()
  File "c:\Program Files\ReText\ReText\xsettings.py", line 174, in get_xsettings
    raw_xsettings = get_raw_xsettings(display)
  File "c:\Program Files\ReText\ReText\xsettings.py", line 51, in get_raw_xsettings
    xcb = ctypes.CDLL(ctypes.util.find_library('xcb'))
  File "C:\Python34\lib\ctypes\__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: bad argument type for built-in operation
```

**Comment by mitya57** [comment]
This is a bug, I will fix it soon. Thanks for the report!

**Comment by team-python** [comment]
to run in windows you need qt5, correct?  did you have build qt5 or did you find an installer package or something?

**Comment by mitya57** [comment]
@team-python The [PyQt5 binary packages](https://riverbankcomputing.com/software/pyqt/download5) will install both Qt and PyQt for you.

**Comment by team-python** [comment]
@mitya57 - thank you!  I will give it a try.
