### ISSUE TITLE
Unable to close preference window after setting markdown extensions

### ISSUE THREAD

**Issue by Vdragon** [retext-project/retext#167]
### Traceback
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/ReText/config.py", line 152, in saveSettings
    self.applySettings()
  File "/usr/local/lib/python3.4/dist-packages/ReText/config.py", line 168, in applySettings
    for tab in self.parent.tabs:
AttributeError: 'ReTextWindow' object has no attribute 'tabs'
```

#### ReText
commit de52271dbe63debd00b91d24d70b63b6cda16419 (post v2.1.2)

#### OS Distribution
Ubuntu 14.04 x86 32-bit

#### Desktop Environment
KDE

#### Python
3.4.0-0ubuntu2

**Comment by Lin-Buo-Ren** [comment]
Seems to be a regression of commit de52271d
