### ISSUE TITLE
PyQt5 issue on Anaconda & WinPython

### ISSUE THREAD

**Issue by dacoex** [retext-project/retext#183]
This is the issue I hit within a virtalenv in WinPython 3
```
In [3]: !virtualenv retext_test
In [15]: Scripts/activate.bat
(retext_test) C:\WinPython-64bit-3.4.3.7\retext_test>pip install retext
Collecting retext
Collecting Pygments (from retext)
  Using cached Pygments-2.1-py3-none-any.whl
Collecting Markdown (from retext)
Collecting Markups (from retext)
Collecting docutils (from retext)
  Downloading docutils-0.12-py3-none-any.whl (508kB)
    100% |################################| 512kB 650kB/s
Collecting pyenchant (from retext)
  Using cached pyenchant-1.6.6-py2.py3-none-any.whl
Installing collected packages: Pygments, Markdown, Markups, docutils, pyenchant, retext
Successfully installed Markdown-2.6.5 Markups-1.0.1 Pygments-2.1 docutils-0.12 pyenchant-1.6.6 retext-5.3.0
You are using pip version 7.1.2, however version 8.0.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

(retext_test) C:\WinPython-64bit-3.4.3.7\retext_test>retext
'retext' is not recognized as an internal or external command,
operable program or batch file.

(retext_test) C:\WinPython-64bit-3.4.3.7\retext_test>python Scripts\retext
Traceback (most recent call last):
  File "Scripts\retext", line 22, in <module>
    from ReText import datadirs, globalSettings, app_version
  File "C:\WinPython-64bit-3.4.3.7\retext_test\lib\site-packages\ReText\__init__.py", line 21, in <module>
    from PyQt5.QtCore import QByteArray, QLocale, QSettings, QStandardPaths
ImportError: No module named 'PyQt5'

(retext_test) C:\WinPython-64bit-3.4.3.7\retext_test>
```

There seems to be an import error with the pip python PyQt5:

```
In [4]: cd Scripts/
C:\WinPython-64bit-3.4.3.7\retext_test\Scripts

In [5]: %run retext
Using configuration file: \HKEY_CURRENT_USER\Software\ReText project\ReText
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
C:\WinPython-64bit-3.4.3.7\retext_test\Scripts\retext in <module>()
     21 from os.path import join
     22 from ReText import datadirs, globalSettings, app_version
---> 23 from ReText.window import ReTextWindow
     24
     25 from PyQt5.QtCore import QFile, QFileInfo, QIODevice, QLibraryInfo, \

C:\WinPython-64bit-3.4.3.7\retext_test\Lib\site-packages\ReText\window.py in <module>()
     20 from ReText import icon_path, app_version, globalSettings, readListFromSettings, \
     21  writeListToSettings, writeToSettings, datadirs, enchant, enchant_available
---> 22 from ReText.tab import ReTextTab, PreviewNormal, PreviewLive
     23 from ReText.dialogs import HtmlDialog, LocaleDialog
     24 from ReText.config import ConfigDialog

C:\WinPython-64bit-3.4.3.7\retext_test\Lib\site-packages\ReText\tab.py in <module>()
     30 from PyQt5.QtGui import QDesktopServices
     31 from PyQt5.QtWidgets import QTextBrowser, QTextEdit, QSplitter
---> 32 from PyQt5.QtWebKit import QWebSettings
     33 from PyQt5.QtWebKitWidgets import QWebPage, QWebView
     34

ImportError: No module named 'PyQt5.QtWebKit'

```

**Comment by mitya57** [comment]
PyQt cannot be installed from PyPI, you need to install it manually.

On Windows, you can use the official installers from the [download page](https://riverbankcomputing.com/software/pyqt/download5).
