### ISSUE TITLE
Crash when changing section title

### ISSUE THREAD

**Issue by farseerfc** [retext-project/retext#207]
ReText from 6.0.0 crashed when I try to change section title. This is very easy to reproduce on my machine with a minimal input:
```
====<wait a second here>
t
```

ReText will crash with error message from console:
```
Using configuration file: /home/farseerfc/.config/ReText project/ReText.conf
<string>:1: (ERROR/3) Document or section may not begin with a transition.
<string>:1: (ERROR/3) Document may not end with a transition.
<string>:1: (ERROR/3) Document or section may not begin with a transition.
<string>:1: (ERROR/3) Document may not end with a transition.
<string>:1: (ERROR/3) Document or section may not begin with a transition.
<string>:1: (ERROR/3) Document may not end with a transition.
<string>:1: (SEVERE/4) Incomplete section title.

=====
t
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/docutils/statemachine.py", line 307, in next_line
    self.line = self.input_lines[self.line_offset]
  File "/usr/lib/python3.5/site-packages/docutils/statemachine.py", line 1152, in __getitem__
    return self.data[i]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2910, in text
    underline = self.state_machine.next_line()
  File "/usr/lib/python3.5/site-packages/docutils/statemachine.py", line 310, in next_line
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/farseerfc/github/retext/ReText/converterprocess.py", line 60, in _converter_process_func
    converted = current_markup.convert(job['text'])
  File "/usr/lib/python3.5/site-packages/markups/restructuredtext.py", line 47, in convert
    writer_name='html', settings_overrides=self.overrides)
  File "/usr/lib/python3.5/site-packages/docutils/core.py", line 448, in publish_parts
    enable_exit_status=enable_exit_status)
  File "/usr/lib/python3.5/site-packages/docutils/core.py", line 662, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/usr/lib/python3.5/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/usr/lib/python3.5/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/usr/lib/python3.5/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python3.5/site-packages/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/usr/lib/python3.5/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3.5/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2919, in text
    line=lineno)
  File "/usr/lib/python3.5/site-packages/docutils/utils/__init__.py", line 235, in severe
    return self.system_message(self.SEVERE_LEVEL, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/docutils/utils/__init__.py", line 193, in system_message
    raise SystemMessage(msg, level)
docutils.utils.SystemMessage: <string>:1: (SEVERE/4) Incomplete section title.

=====
t
Traceback (most recent call last):
  File "/home/farseerfc/github/retext/ReText/tab.py", line 233, in updatePreviewBox
    self.converted = self.converterProcess.get_result()
  File "/home/farseerfc/github/retext/ReText/converterprocess.py", line 136, in get_result
    status, converted = receiveObject(self.conn)
  File "/home/farseerfc/github/retext/ReText/converterprocess.py", line 24, in receiveObject
    sizeBuf = recvall(sock, 4)
  File "/home/farseerfc/github/retext/ReText/converterprocess.py", line 17, in recvall
    raise EOFError('Received 0 bytes from socket while more bytes were expected. Did the sender process exit unexpectedly?')
EOFError: Received 0 bytes from socket while more bytes were expected. Did the sender process exit unexpectedly?
[1]    20461 abort (core dumped)  python retext.py
```

I can reproduce this problem using both 6.0.0 tarbar and latest master branch (7b7db8f674f9a63602479b9101d0e0a2ea74aadb)

**Comment by Griffon26** [comment]
Thanks for reporting this issue. The fix I committed should take care of this problem.

**Comment by farseerfc** [comment]
Thank you for a quick fix! Have tested that the commit fixed this bug.
