### ISSUE TITLE
Not responding if starting from KDE5 Plasma

### ISSUE THREAD

**Issue by farseerfc** [retext-project/retext#237]
Hi, some user of Arch Linux reported this problem to me and I confirmed that I can always reproduce it, but I cannot determine whether it is a bug of ReText or a bug of packaging.

If starting retext from KDE5 Plasma, the main window of retext will be non-responding, and eventually kwin will prompted the user to kill it.
This can be reproducible from both "Application Launcher" of Plasma and krunner, using the desktop file.
If starting retext from konsole or other terminals, retext will launch normally without any problems.

I haven't test it from other DEs.

The desktop file is packaged from this file:
https://github.com/retext-project/retext/blob/08a06ba43405178969c495a108856a731ca9822a/data/me.mitya57.ReText.desktop
And this file is installed at `/usr/share/applications`.

**Comment by mitya57** [comment]
Can you please provide a (Python and/or C++) traceback of what happens when it hangs?

I.e. try to start ReText from the console, then press <kbd>Ctrl</kbd>+<kbd>C</kbd> and paste the output.

**Comment by farseerfc** [comment]
Starting ReText from console will launch it normally.
I tried to start ReText from krunner with `bash -c "retext 2>&1 >/tmp/retext.log"`, the file `/tmp/retext.log` is created but its content is empty (before and after kwin killed retext).

Attaching gdb after it hangs did work, I will paste bt here:
```
sudo gdb -p $(pgrep retext)
GNU gdb (GDB) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Attaching to process 3372
[New LWP 3373]
[New LWP 3374]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007ff6590831cd in read () from /usr/lib/libpthread.so.0
(gdb) bt
#0  0x00007ff6590831cd in read () from /usr/lib/libpthread.so.0
#1  0x00007ff6593ed0b6 in _Py_read () from /usr/lib/libpython3.5m.so.1.0
#2  0x00007ff659428142 in ?? () from /usr/lib/libpython3.5m.so.1.0
#3  0x00007ff65933f891 in PyCFunction_Call () from /usr/lib/libpython3.5m.so.1.0
#4  0x00007ff6592f82d7 in PyObject_Call () from /usr/lib/libpython3.5m.so.1.0
#5  0x00007ff6592f8bf4 in PyObject_CallMethodObjArgs () from /usr/lib/libpython3.5m.so.1.0
#6  0x00007ff65942dafd in ?? () from /usr/lib/libpython3.5m.so.1.0
#7  0x00007ff65933f8a9 in PyCFunction_Call () from /usr/lib/libpython3.5m.so.1.0
#8  0x00007ff6592f82d7 in PyObject_Call () from /usr/lib/libpython3.5m.so.1.0
#9  0x00007ff6592f83c5 in ?? () from /usr/lib/libpython3.5m.so.1.0
#10 0x00007ff6592f845c in ?? () from /usr/lib/libpython3.5m.so.1.0
#11 0x00007ff6592f8ac8 in _PyObject_CallMethodId_SizeT () from /usr/lib/libpython3.5m.so.1.0
#12 0x00007ff659432b74 in ?? () from /usr/lib/libpython3.5m.so.1.0
#13 0x00007ff65933f8a9 in PyCFunction_Call () from /usr/lib/libpython3.5m.so.1.0
#14 0x00007ff6593b747b in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
#15 0x00007ff6593b82c3 in ?? () from /usr/lib/libpython3.5m.so.1.0
#16 0x00007ff6593b4b0e in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
#17 0x00007ff6593b82c3 in ?? () from /usr/lib/libpython3.5m.so.1.0
#18 0x00007ff6593b83a3 in PyEval_EvalCodeEx () from /usr/lib/libpython3.5m.so.1.0
#19 0x00007ff6593b83cb in PyEval_EvalCode () from /usr/lib/libpython3.5m.so.1.0
#20 0x00007ff6593d7364 in ?? () from /usr/lib/libpython3.5m.so.1.0
#21 0x00007ff6593d98e5 in PyRun_FileExFlags () from /usr/lib/libpython3.5m.so.1.0
#22 0x00007ff6593d9a55 in PyRun_SimpleFileExFlags () from /usr/lib/libpython3.5m.so.1.0
#23 0x00007ff6593f069c in Py_Main () from /usr/lib/libpython3.5m.so.1.0
#24 0x0000000000400af0 in main ()
```
But I have no idea what is going on from this backtrace... sorry

**Comment by mitya57** [comment]
Fixed now. Sorry for the delay. I will try to make a new bugfix release out soon.

**Comment by farseerfc** [comment]
thanks!
