### ISSUE TITLE
Crashes when try to change font.

### ISSUE THREAD

**Issue by shawn-peng** [retext-project/retext#247]
Hi,

When I tried to change the font, the program crashes with a segmentation fault.
Operation:
Menu > Edit > Change preview font (or change editor font)

Version:
Version     : 6.0.2
Release     : 1.fc25

Here is the debuginfo,

```
(python3:4635): Gtk-WARNING **: Unknown type PangoFontFamily specified in treemodel model

(python3:4635): Gtk-WARNING **: Unknown type PangoFontFace specified in treemodel model

(python3:4635): Gtk-WARNING **: gtkliststore.c:516: Invalid type (null)

(python3:4635): Gtk-WARNING **: gtkliststore.c:516: Invalid type (null)

(python3:4635): GLib-GObject-CRITICAL **: g_value_type_transformable: assertion 'G_TYPE_IS_VALUE (src_type)' failed

(python3:4635): GLib-GObject-CRITICAL **: g_value_type_transformable: assertion 'G_TYPE_IS_VALUE (src_type)' failed

(python3:4635): GLib-GObject-WARNING **: gtype.c:4264: type id '0' is invalid

(python3:4635): GLib-GObject-WARNING **: can't peek value table for type '<invalid>' which is not currently referenced
Process Process-1:
[1]    4635 segmentation fault (core dumped)  retext
Traceback (most recent call last):                                                     
  File "/usr/lib64/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib64/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/ReText/converterprocess.py", line 62, in _converter_process_func
    job = receiveObject(conn_child)
  File "/usr/lib/python3.5/site-packages/ReText/converterprocess.py", line 31, in receiveObject
    sizeBuf = recvall(sock, 4)
  File "/usr/lib/python3.5/site-packages/ReText/converterprocess.py", line 24, in recvall
    raise EOFError('Received 0 bytes from socket while more bytes were expected. Did the sender process exit unexpectedly?')
EOFError: Received 0 bytes from socket while more bytes were expected. Did the sender process exit unexpectedly?

```

Thanks,
Yisu

**Comment by shawn-peng** [comment]
BTW, I think only the config of font size is enough.

**Comment by mitya57** [comment]
Thanks for the report! I can reproduce it with QGnomePlatform theme, will debug a bit later.

As a workaround, you can start ReText with `QT_QPA_PLATFORMTHEME=generic` environment variable set.

**Comment by mitya57** [comment]
I have now created a pull request to QGnomePlatform that fixes the crash. This bug is now closed, because it is not a bug in ReText itself.
