### ISSUE TITLE
Segfault When CSS File Has Been Deleted

### ISSUE THREAD

**Issue by MorganRodgers** [retext-project/retext#312]
Retext (5.0.1) will segfault without ever showing a window if the CSS file expected by `readColorSchemeFromFile` does not exist.

> QIODevice::read: device not open
Traceback (most recent call last):
  File "/usr/bin/retext", line 76, in <module>
    main()
  File "/usr/bin/retext", line 71, in main
    window.createNew(inputData)
  File "/usr/share/retext/ReText/window.py", line 751, in createNew
    self.tabWidget.addTab(self.createTab(""), self.tr("New document"))
  File "/usr/share/retext/ReText/window.py", line 391, in createTab
    self.highlighters.append(ReTextHighlighter(self.editBoxes[-1].document()))
  File "/usr/share/retext/ReText/highlighter.py", line 74, in __init__
    updateColorScheme()
  File "/usr/share/retext/ReText/highlighter.py", line 64, in updateColorScheme
    colorScheme = readColorSchemeFromFile(newSchemeFile)
  File "/usr/share/retext/ReText/highlighter.py", line 50, in readColorSchemeFromFile
    schemefile = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/morgan/Desktop/github_markdown.css'
Segmentation fault

While an old version, 5.0.1 is the version that the Linux Mint repos point to.

**Comment by mitya57** [comment]
This is fixed in ReText 5.3: the color scheme is no longer a separate file, but part of the main configuration file.

The latest Linux Mint is based on Ubuntu 16.04, so it should have ReText 5.3.1 (still old, but with this fix).
