### ISSUE TITLE
Installation does not work on Linux Mint 18.3

### ISSUE THREAD

**Issue by SweRavn** [retext-project/retext#364]
I get:

Using configuration file: /home/XXX/.config/ReText project/ReText.conf
Traceback (most recent call last):
  File "/usr/bin/retext", line 23, in <module>
    from ReText.window import ReTextWindow
  File "/usr/share/retext/ReText/window.py", line 22, in <module>
    from ReText.tab import ReTextTab, PreviewNormal, PreviewLive
  File "/usr/share/retext/ReText/tab.py", line 32, in <module>
    from PyQt5.QtWebKit import QWebSettings
ImportError: No module named 'PyQt5.QtWebKit'

I have QtWebKit installed:
i A python3-pyqt5.qtwebkit                                     - Python 3 bindings for Qt5's WebKit module

**Comment by mitya57** [comment]
This most likely means that you have a custom installation of PyQt5 somewhere, that does not support Qt WebKit. I recommend you to check your `~/.local/lib/python3.5/site-packages/` and `/usr/local/lib/python3.5/site-packages/` directories.

In any case, the latest versions of ReText (6.0 and newer) can run without Qt WebKit installed. Linux Mint just ships an outdated version of ReText.
