### ISSUE TITLE
ReText hangs or crashes when embedding large images using html

### ISSUE THREAD

**Issue by holzkohlengrill** [retext-project/retext#389]
When embedding large images into documents (no preview active) it seems that it is getting loaded within the main thread (btw. why is it loaded anyway and not only the reference/path to it). This might freeze ReText for a while or let it crash. Example code:

```
<div align="center">
<img src="bigImage.png" height="330" />
</div>
```

---

```
$identify bigImage.png
bigImage.png PNG 13244x9354 13244x9354+0+0 8-bit sRGB 19.6964MiB 0.000u 0:00.009
```

ReText: 7.1.0 (Git)
PyMarkups: 3.0.0
Qt: 5.10.1
Python: 3.7.0b5

**Comment by mitya57** [comment]
Can you please attach your image or upload it somewhere?

Also, if this is a crash, maybe you can obtain a stack trace? The easiest is the [stacktrace from Python](https://docs.python.org/3/library/faulthandler.html#example) when you run python with `-X faulthandler`, but a proper stacktrace from debugger will also help.

**Comment by holzkohlengrill** [comment]
I could not reproduce the crash anymore but the freezing with `-X faulthandler` enabled and with an image I can share (as the console output says the reason is probably just the high resolution). My initial image was generated from a SVG. That's why I ended up with this extremely high resolution.

What `-X faulthandler` outputs is the following: `QImage: out of memory, returning null image`.
Before I saw also `QFSFileEngine::open: No file name specified`. This is because I hat a typo in the path.

Full output:
```
$ python.exe -X faulthandler ./retext.py
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
QImage: out of memory, returning null image
Process Process-1:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Program Files (x86)\Python37-32\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\holzkohlengrill\AppData\Local\Programs\retext\ReText\converterprocess.py", line 63, in _converter_process_func
    job = receiveObject(conn_child)
  File "C:\Users\holzkohlengrill\AppData\Local\Programs\retext\ReText\converterprocess.py", line 32, in receiveObject
    sizeBuf = recvall(sock, 4)
  File "C:\Users\holzkkohlengrill\AppData\Local\Programs\retext\ReText\converterprocess.py", line 23, in recvall
    data = sock.recv(remaining)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
```

**Comment by mitya57** [comment]
Somehow this issue got lost in my mailbox. Now I am reviewing old issues and got back to it.

> Somehow I cannot load this [image](https://upload.wikimedia.org/wikipedia/commons/2/24/Krater_with_Electra_-_MAN.jpg). I always get `QFSFileEngine::open: No file name specified`. Does it work for you?

Have you downloaded that image locally, or you are trying to load a remote image? I think such error may happen when the image is remote and you are using QTextBrowser viewer (not WebKit). That viewer does not support remote images at all. Or there is a typo somewhere in the file path…

Anyway, I just tried to open that file in a regular image viewer (eog) and it made my laptop hang. Looks like 4GB memory is not enough for it. So better I won't even try with ReText.

> QImage: out of memory, returning null image

I doubt I can do anything about this. ReText uses Qt, which in turn uses libjpeg-turbo, so if there is inadequate memory consumption, it most probably lies in one of these two libraries.

Can you try to open the image in a file viewer using Qt, such as gwenview?

**Comment by holzkohlengrill** [comment]
I only tested it with the Windows file viewer and on Xubuntu with ristretto and viewing the image was just fine.

![image](https://user-images.githubusercontent.com/12732886/71985738-6eac7580-322b-11ea-9cb0-9a866e47237b.png)

![image](https://user-images.githubusercontent.com/12732886/71985793-871c9000-322b-11ea-846b-47a4f6ad9d7a.png)

Tried it with eog:
Wow, it seems that Qt handles that very inefficiently. `eog` eats up all the memory and then just crashes.

I have the image locally (no remote loading).

**Comment by monperrus** [comment]
I'm using `![](img.png)` but `img.png` is a large image with high resolution.

How to force retext to fit the image width to the preview width?

Thanks!

**Comment by mitya57** [comment]
@monperrus ReText in master already includes a style to fit images in preview:
https://github.com/retext-project/retext/blob/16f15df808d8af077b38cd27c5878b5eb64f4cc2/ReText/tab.py#L204

In stable version you can achieve this by using [attribute lists][1]:

    ![caption](img.png){: width="100%" }

[1]: https://python-markdown.github.io/extensions/attr_list/

**Comment by monperrus** [comment]
great, thanks. any idea on when the debian package will be updated to master?

**Comment by mitya57** [comment]
Maybe in February…
