### ISSUE TITLE
Crash when rightclicking on header line

### ISSUE THREAD

**Issue by kannes** [retext-project/retext#403]
1. Make a new document with the whole content being `#a`.

2. Rightclick between the characters. 

3. Retext crashes:

```

$ retext 
Using configuration file: /home/user/.config/ReText project/ReText.conf
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ReText/editor.py", line 195, in contextMenuEvent
    if word is not None and not dictionary.check(word):
AttributeError: 'NoneType' object has no attribute 'check'
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/site-packages/ReText/converterprocess.py", line 63, in _converter_process_func
    job = receiveObject(conn_child)
  File "/usr/lib/python3.7/site-packages/ReText/converterprocess.py", line 32, in receiveObject
    sizeBuf = recvall(sock, 4)
  File "/usr/lib/python3.7/site-packages/ReText/converterprocess.py", line 25, in recvall
    raise EOFError('Received 0 bytes from socket while more bytes were expected. Did the sender process exit unexpectedly?')
Aborted (core dumped)
EOFError: Received 0 bytes from socket while more bytes were expected. Did the sender process exit unexpectedly?
$ 
```
ReText 7.1.0 (Git) (using PyMarkups 3.0.0) on Archlinux (retext-git, 7.0.0.r103.g37923cb-1).

**Comment by mitya57** [comment]
Thanks for the report, it is fixed now.

The crash only happened when the spell checker was not available. As a workaround, install `python-pyenchant` package and it will be available.

**Comment by mitya57** [comment]
Note: this does not affect the stable branch (7.0) as the bug was introduced only in #337.

**Comment by kannes** [comment]
Wow, that was quick, thanks!
