### ISSUE TITLE
Preview not working

### ISSUE THREAD

**Issue by Blackhawke** [retext-project/retext#423]
ReText was working wonderfully, but I wanted a bit more preprocessing of HTML, so I installed the markdown extension mdx_smartypants. And... preview quit working. So... I uninstalled the extension, thinking things would return to normal, but still no preview. Then I uninstalled/reinstalled ReText. Same outcome. No preview.

Running Ubuntu 18.04.

**Comment by Blackhawke** [comment]
Forgot to leave the log entries:

> Dec 16 15:29:34 metaphorpublications org.gnome.Nautilus[5513]: Exception occurre
> d while parsing document:
> Dec 16 15:29:34 metaphorpublications org.gnome.Nautilus[5513]: Traceback (most r
> ecent call last):
> Dec 16 15:29:34 metaphorpublications org.gnome.Nautilus[5513]:   File "/usr/shar
> e/retext/ReText/tab.py", line 228, in updatePreviewBox
> Dec 16 15:29:34 metaphorpublications org.gnome.Nautilus[5513]:     self.converte
> d = self.converterProcess.get_result()
> Dec 16 15:29:34 metaphorpublications org.gnome.Nautilus[5513]:   File "/usr/shar
> e/retext/ReText/converterprocess.py", line 172, in get_result
> Dec 16 15:29:34 metaphorpublications org.gnome.Nautilus[5513]:     raise Convers
> ionError(result)
> Dec 16 15:29:34 metaphorpublications org.gnome.Nautilus[5513]: ReText.converterp
> rocess.ConversionError: The background markup conversion process received this e
> xception:
> Dec 16 15:29:34 metaphorpublications org.gnome.Nautilus[5513]:     Traceback (mo
> st recent call last):
> Dec 16 15:29:34 metaphorpublications org.gnome.Nautilus[5513]:       File "/usr/
> share/retext/ReText/converterprocess.py", line 74, in _converter_process_func

**Comment by mitya57** [comment]
Can you please attach a few more lines of the log? The actual error is not visible here.

Or start `retext` from Terminal, trigger the crash, and paste the output from Terminal here.

**Comment by Blackhawke** [comment]
My apologies for taking so long to answer. I've been out of town.

Here's the terminal output:

> Using configuration file: /home/******/.config/ReText project/ReText.conf
> libpng warning: iCCP: known incorrect sRGB profile
> libpng warning: iCCP: known incorrect sRGB profile
> Exception occurred while parsing document:
> Traceback (most recent call last):
>   File "/usr/share/retext/ReText/tab.py", line 228, in updatePreviewBox
>     self.converted = self.converterProcess.get_result()
>   File "/usr/share/retext/ReText/converterprocess.py", line 172, in get_result
>     raise ConversionError(result)
> ReText.converterprocess.ConversionError: The background markup conversion process received this exception:
>     Traceback (most recent call last):
>       File "/usr/share/retext/ReText/converterprocess.py", line 74, in _converter_process_func
>         current_markup = markup_class(job['filename'])
>       File "/usr/lib/python3/dist-packages/markups/markdown.py", line 146, in __init__
>         self._apply_extensions()
>       File "/usr/lib/python3/dist-packages/markups/markdown.py", line 132, in _apply_extensions
>         self.md = self.markdown.Markdown(extensions=extensions_final, output_format='html4')
>       File "/usr/local/lib/python3.6/dist-packages/markdown/core.py", line 100, in __init__
>         configs=kwargs.get('extension_configs', {}))
>       File "/usr/local/lib/python3.6/dist-packages/markdown/core.py", line 126, in registerExtensions
>         ext = self.build_extension(ext, configs.get(ext, {}))
>       File "/usr/local/lib/python3.6/dist-packages/markdown/core.py", line 166, in build_extension
>         module = importlib.import_module(ext_name)
>       File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
>         return _bootstrap._gcd_import(name[level:], package, level)
>       File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>       File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>       File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
>     ModuleNotFoundError: No module named 'markups.mdx_mathjax(enable_dollar_delimiter=False)'

**Comment by robtow-wattzon** [comment]
Live preview **was** working, then stopped. I had an open document that I _was_ able to preview, then I closed `retext`, restarted the app, and re-opened the doc; no preview.

Starting `retext` from the command line produces this output:

```
rob@ubuntu:~$ retext

(python3:15082): Gtk-WARNING **: 13:53:10.301: Theme parsing error: gtk.css:1:8: Expected a valid selector

(python3:15082): Gtk-WARNING **: 13:53:10.302: Theme parsing error: gtk.css:11:2: Expected a valid selector
Using configuration file: /home/rob/.config/ReText project/ReText.conf
Exception occurred while parsing document:
Traceback (most recent call last):
  File "/usr/share/retext/ReText/tab.py", line 228, in updatePreviewBox
    self.converted = self.converterProcess.get_result()
  File "/usr/share/retext/ReText/converterprocess.py", line 172, in get_result
    raise ConversionError(result)
ReText.converterprocess.ConversionError: The background markup conversion process received this exception:
    Traceback (most recent call last):
      File "/usr/share/retext/ReText/converterprocess.py", line 74, in _converter_process_func
        current_markup = markup_class(job['filename'])
      File "/usr/lib/python3/dist-packages/markups/markdown.py", line 146, in __init__
        self._apply_extensions()
      File "/usr/lib/python3/dist-packages/markups/markdown.py", line 132, in _apply_extensions
        self.md = self.markdown.Markdown(extensions=extensions_final, output_format='html4')
      File "/home/rob/.local/lib/python3.6/site-packages/markdown/core.py", line 100, in __init__
        configs=kwargs.get('extension_configs', {}))
      File "/home/rob/.local/lib/python3.6/site-packages/markdown/core.py", line 126, in registerExtensions
        ext = self.build_extension(ext, configs.get(ext, {}))
      File "/home/rob/.local/lib/python3.6/site-packages/markdown/core.py", line 166, in build_extension
        module = importlib.import_module(ext_name)
      File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'markups.mdx_mathjax(enable_dollar_delimiter=False)'

Exception occurred while parsing document:
Traceback (most recent call last):
  File "/usr/share/retext/ReText/tab.py", line 228, in updatePreviewBox
    self.converted = self.converterProcess.get_result()
  File "/usr/share/retext/ReText/converterprocess.py", line 172, in get_result
    raise ConversionError(result)
ReText.converterprocess.ConversionError: The background markup conversion process received this exception:
    Traceback (most recent call last):
      File "/usr/share/retext/ReText/converterprocess.py", line 74, in _converter_process_func
        current_markup = markup_class(job['filename'])
      File "/usr/lib/python3/dist-packages/markups/markdown.py", line 146, in __init__
        self._apply_extensions()
      File "/usr/lib/python3/dist-packages/markups/markdown.py", line 132, in _apply_extensions
        self.md = self.markdown.Markdown(extensions=extensions_final, output_format='html4')
      File "/home/rob/.local/lib/python3.6/site-packages/markdown/core.py", line 100, in __init__
        configs=kwargs.get('extension_configs', {}))
      File "/home/rob/.local/lib/python3.6/site-packages/markdown/core.py", line 126, in registerExtensions
        ext = self.build_extension(ext, configs.get(ext, {}))
      File "/home/rob/.local/lib/python3.6/site-packages/markdown/core.py", line 166, in build_extension
        module = importlib.import_module(ext_name)
      File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'markups.mdx_mathjax(enable_dollar_delimiter=False)'
```

**Comment by mitya57** [comment]
It looks like you are mixing ReText from your distro's repository and Python-Markdown and Markups from PyPI. That is a bad idea.

Try cleaning up everything in `/usr/local/lib/python3.6/` and `/home/rob/.local/lib/python3.6/`, then it should work fine.

Alternatively, if you want the latest versions, clean up the former directory and then run this:

    $ pip3 install --user --upgrade Markdown Markups ReText

**Comment by Rmano** [comment]
Hi --- the 

     sudo pip install --upgrade Markups

worked for me, but 

      pip3 install --user --upgrade Markdown Markups ReText 

ended with 

``` Downloading https://files.pythonhosted.org/packages/4d/81/b9a66a28fb9a7bbeb60e266f06ebc4703e7e42b99e3609bf1b58ddd232b9/PyQt5-5.14.2.tar.gz (3.2MB)
    100% |████████████████████████████████| 3.3MB 506kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-vtgjrr9p/PyQt5/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vtgjrr9p/PyQt5/
```

**Comment by mitya57** [comment]
@Rmano Most likely you have an old version of pip. Please upgrade pip and setuptools to the latest versions first.
