### ISSUE TITLE
Getting AttributeError while previewing a file

### ISSUE THREAD

**Issue by VardhanThigle** [retext-project/retext#434]
```
vardhan@vardhan-ThinkPad-T470:~$ retext ~/Work/TODOS/running_todos_3.md
Using configuration file: /home/vardhan/.config/ReText project/ReText.conf
Exception occured while parsing document:
Traceback (most recent call last):
  File "/usr/share/retext/ReText/tab.py", line 108, in getDocumentTitle
    return self.markup.get_document_title(text)
AttributeError: 'MarkdownMarkup' object has no attribute 'get_document_title'
Exception occured while parsing document:
Traceback (most recent call last):
  File "/usr/share/retext/ReText/tab.py", line 156, in updatePreviewBox
    html = self.getHtml()
  File "/usr/share/retext/ReText/tab.py", line 142, in getHtml
    return self.markup.get_whole_html(text,
AttributeError: 'MarkdownMarkup' object has no attribute 'get_whole_html'
```

**Comment by mitya57** [comment]
You seem to be using an old version of ReText (< 6.0) with a new version of PyMarkups (≥ 3.0). This is incompatible.

It also looks like your ReText is installed from the distro packages (Debian/Ubuntu), but PyMarkups is installed from PyPI. Please install both packages from the same source (if it is distro packages, then uninstall the PyPI version), that should solve your problem.

**Comment by VardhanThigle** [comment]
Thanks. Worked.
