### ISSUE TITLE
Live preview not working. Need to clarify solution to previous Issue.

### ISSUE THREAD

**Issue by scottfurry** [retext-project/retext#454]
Reference: Issue #423 
On Gentoo-base derivative and have installed retext from their instructions. I am currently experiencing similar problem with ReText as Issue #423 and am attempting to resolve locally. Researching problem I found issue but am unclear of resolution. Final post to above issue indicated incompatibility between **markups** and **markdown** python modules, if I'm reading this correctly.

Currently installed:
markups (from distribution) - ver: 2.0.0
markdown(from distribution) - ver: 3.0.1
retext(from distribution) - ver: 7.0.3

pip not used!

Reported error from retext:
```
Exception occurred while parsing document:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/ReText/tab.py", line 228, in updatePreviewBox
    self.converted = self.converterProcess.get_result()
  File "/usr/lib64/python3.6/site-packages/ReText/converterprocess.py", line 172, in get_result
    raise ConversionError(result)
ReText.converterprocess.ConversionError: The background markup conversion process received this exception:
    Traceback (most recent call last):
      File "/usr/lib64/python3.6/site-packages/ReText/converterprocess.py", line 74, in _converter_process_func
        current_markup = markup_class(job['filename'])
      File "/usr/lib64/python3.6/site-packages/markups/markdown.py", line 145, in __init__
        self._apply_extensions()
      File "/usr/lib64/python3.6/site-packages/markups/markdown.py", line 131, in _apply_extensions
        self.md = self.markdown.Markdown(extensions=extensions_final, output_format='html4')
      File "/usr/lib64/python3.6/site-packages/markdown/core.py", line 100, in __init__
        configs=kwargs.get('extension_configs', {}))
      File "/usr/lib64/python3.6/site-packages/markdown/core.py", line 126, in registerExtensions
        ext = self.build_extension(ext, configs.get(ext, {}))
      File "/usr/lib64/python3.6/site-packages/markdown/core.py", line 166, in build_extension
        module = importlib.import_module(ext_name)
      File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'markups.mdx_mathjax(enable_dollar_delimiter=False)'
```

**Comment by scottfurry** [comment]
...nevermind...
Further down in search results was a link to an openSUSE mailing list item
https://marc.info/?l=opensuse&m=155194076017230&w=2
User was stating quite clearly that **markups** version 3 is required for retext version >=7.

Distribution needs updated instructions for python markups module.
