### ISSUE TITLE
AttributeError: module 'pkg_resources._vendor.packaging' has no attribute 'version'`

### ISSUE THREAD

**Issue by triswan** [retext-project/retext#458]
Hi, i run retext on up-to-date arch linux, and got this:

```
Traceback (most recent call last):
  File "/usr/bin/retext", line 11, in <module>
    load_entry_point('ReText==7.1.0', 'gui_scripts', 'retext')()
  File "/usr/lib/python3.7/site-packages/ReText/__main__.py", line 88, in main
    window = ReTextWindow()
  File "/usr/lib/python3.7/site-packages/ReText/window.py", line 232, in __init__
    availableMarkups = markups.get_available_markups()
  File "/usr/lib/python3.7/site-packages/markups/__init__.py", line 34, in get_available_markups
    if markup.available():
  File "/usr/lib/python3.7/site-packages/markups/markdown.py", line 55, in available
    import markdown
  File "/usr/lib/python3.7/site-packages/markdown/__init__.py", line 67, in <module>
    __version__ = _get_version()
  File "/usr/lib/python3.7/site-packages/markdown/__init__.py", line 64, in _get_version
    return str(packaging.version.Version(v))
AttributeError: module 'pkg_resources._vendor.packaging' has no attribute 'version'
```

Any help is appreciated

**Comment by mitya57** [comment]
Can it be that you have an old version (older than 36.6) of setuptools or pkg_resources installed somewhere?

Can you please run a Python interpreter and tell me what is the output of this?
```python
>>> import pkg_resources
>>> print(pkg_resources.__path__)
>>> import setuptools
>>> print(setuptools.__version__)
>>> print(setuptools.__path__)
>>> from pkg_resources.extern import packaging
>>> print(packaging.version.Version("3.1"))

**Comment by triswan** [comment]
here it is

```
$ python
Python 3.7.3 (default, Mar 26 2019, 21:43:19) 
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
>>> print(pkg_resources.__path__)
['/usr/lib/python3.7/site-packages/pkg_resources']
>>> import setuptools
>>> print(setuptools.__version__)
41.0.1
>>> print(setuptools.__path__)
['/usr/lib/python3.7/site-packages/setuptools']
>>> from pkg_resources.extern import packaging
>>> print(packaging.version.Version("3.1"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pkg_resources._vendor.packaging' has no attribute 'version'
>>> 
```

**Comment by mitya57** [comment]
Thanks! It looks like the issue is that python-markdown module is using setuptools’ vendored version of packaging, and ArchLinux removes it in its PKGBUILD.

I have just filed a bug against python-markdown, see python-markdown/markdown#825.

Unfortunately, there is nothing I can do in ReText to fix this, as it's an upstream issue. As a workaround, you can manually edit `/usr/lib/python3.7/site-packages/markdown/__init__.py` file and replace line 28
```python
from pkg_resources.extern import packaging
```
with just
```python
import packaging
```

**Comment by mitya57** [comment]
Ah, and as your Python-Markdown build also comes from ArchLinux, you can file a bug against the packaging so that the ArchLinux maintainers replace the import before it's done upstream.

**Comment by triswan** [comment]
Thanks for your help...
The workaround is working and I'll try to report this issue to ArchLinux

**Comment by mitya57** [comment]
Please add a link to https://github.com/Python-Markdown/markdown/issues/825 in your report :)
