### ISSUE TITLE
preview show blank

### ISSUE THREAD

**Issue by eexpress** [retext-project/retext#481]
fedora 31 here. 

```
/usr/lib/python3.7/site-packages/ReText/window.py:366: RuntimeWarning: Dictionary for language 'zh_CN' could not be found
  warnings.warn(str(e), RuntimeWarning)
Exception occurred while parsing document:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ReText/tab.py", line 228, in updatePreviewBox
    self.converted = self.converterProcess.get_result()
  File "/usr/lib/python3.7/site-packages/ReText/converterprocess.py", line 172, in get_result
    raise ConversionError(result)
ReText.converterprocess.ConversionError: The background markup conversion process received this exception:
    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/ReText/converterprocess.py", line 74, in _converter_process_func
        current_markup = markup_class(job['filename'])
      File "/usr/lib/python3.7/site-packages/markups/markdown.py", line 145, in __init__
        self._apply_extensions()
      File "/usr/lib/python3.7/site-packages/markups/markdown.py", line 131, in _apply_extensions
        self.md = self.markdown.Markdown(extensions=extensions_final, output_format='html4')
      File "/usr/lib/python3.7/site-packages/markdown/core.py", line 100, in __init__
        configs=kwargs.get('extension_configs', {}))
      File "/usr/lib/python3.7/site-packages/markdown/core.py", line 126, in registerExtensions
        ext = self.build_extension(ext, configs.get(ext, {}))
      File "/usr/lib/python3.7/site-packages/markdown/core.py", line 166, in build_extension
        module = importlib.import_module(ext_name)
      File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'markups.mdx_mathjax(enable_dollar_delimiter=False)'
```

**Comment by mitya57** [comment]
Please try updating python-markups to version 3.0.0. Older python-markups won't work with Python-Markdown 3.x.

**Comment by eexpress** [comment]
no "python-markups" in fedora repo. :(

**Comment by mitya57** [comment]
But Fedora neither has ReText? According to [their page](https://apps.fedoraproject.org/packages/retext) the package was orphaned and then removed.

So you can install it from PyPI:

    $ pip3 install --user --upgrade Markups ReText

**Comment by eexpress** [comment]
sad.. OK, i will try this.
