### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by sevku** [retext-project/retext#495]
```
$ ./setup.py install --user
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/ReText
copying ReText/fakevimeditor.py -> build/lib/ReText
copying ReText/__main__.py -> build/lib/ReText
copying ReText/window.py -> build/lib/ReText
copying ReText/webkitpreview.py -> build/lib/ReText
copying ReText/__init__.py -> build/lib/ReText
copying ReText/icontheme.py -> build/lib/ReText
copying ReText/converterprocess.py -> build/lib/ReText
copying ReText/xsettings.py -> build/lib/ReText
copying ReText/webenginepreview.py -> build/lib/ReText
copying ReText/config.py -> build/lib/ReText
copying ReText/syncscroll.py -> build/lib/ReText
copying ReText/tabledialog.py -> build/lib/ReText
copying ReText/tablemode.py -> build/lib/ReText
copying ReText/mdx_posmap.py -> build/lib/ReText
copying ReText/preview.py -> build/lib/ReText
copying ReText/dialogs.py -> build/lib/ReText
copying ReText/tab.py -> build/lib/ReText
copying ReText/highlighter.py -> build/lib/ReText
copying ReText/editor.py -> build/lib/ReText
running build_translations
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory
Failed to build translations: Command '('lrelease', 'locale/retext_uk.ts')' returned non-zero exit status 1.
running install_lib
creating /home/$USER/.local/lib/python3.7/site-packages/ReText
copying build/lib/ReText/fakevimeditor.py -> /home/$USER/.local/lib/python3.7/site-packages/ReText
copying build/lib/ReText/__main__.py -> /home/$USER/.local/lib/python3.7/site-packages/ReText
copying build/lib/ReText/window.py -> /home/$USER/.local/lib/python3.7/site-packages/ReText
copying build/lib/ReText/webkitpreview.py -> /home/$USER/.local/lib/python3.7/site-packages/ReText
copying build/lib/ReText/__init__.py -> /home/$USER/.local/lib/python3.7/site-packages/ReText
copying build/lib/ReText/icontheme.py -> /home/$USER/.local/lib/python3.7/site-packages/ReText
copying build/lib/ReText/converterprocess.py -> /home/$USER/.local/lib/python3.7/site-packages/ReText
copying build/lib/ReText/xsettings.py -> /home/$USER/.local/lib/python3.7/site-packages/ReText
copying build/lib/ReText/webenginepreview.py -> /home/$USER/.local/lib/python3.7/site-packages/ReText
copying build/lib/ReText/config.py -> /home/$USER/.local/lib/python3.7/site-packages/ReText
copying build/lib/ReText/syncscroll.py -> /home/$USER/.local/lib/python3.7/site-packages/ReText
copying build/lib/ReText/tabledialog.py -> /home/$USER/.local/lib/python3.7/site-packages/ReText
copying build/lib/ReText/tablemode.py -> /home/$USER/.local/lib/python3.7/site-packages/ReText
copying build/lib/ReText/mdx_posmap.py -> /home/$USER/.local/lib/python3.7/site-packages/ReText
copying build/lib/ReText/preview.py -> /home/$USER/.local/lib/python3.7/site-packages/ReText
copying build/lib/ReText/dialogs.py -> /home/$USER/.local/lib/python3.7/site-packages/ReText
copying build/lib/ReText/tab.py -> /home/$USER/.local/lib/python3.7/site-packages/ReText
copying build/lib/ReText/highlighter.py -> /home/$USER/.local/lib/python3.7/site-packages/ReText
copying build/lib/ReText/editor.py -> /home/$USER/.local/lib/python3.7/site-packages/ReText
byte-compiling /home/$USER/.local/lib/python3.7/site-packages/ReText/fakevimeditor.py to fakevimeditor.cpython-37.pyc
byte-compiling /home/$USER/.local/lib/python3.7/site-packages/ReText/__main__.py to __main__.cpython-37.pyc
byte-compiling /home/$USER/.local/lib/python3.7/site-packages/ReText/window.py to window.cpython-37.pyc
byte-compiling /home/$USER/.local/lib/python3.7/site-packages/ReText/webkitpreview.py to webkitpreview.cpython-37.pyc
byte-compiling /home/$USER/.local/lib/python3.7/site-packages/ReText/__init__.py to __init__.cpython-37.pyc
byte-compiling /home/$USER/.local/lib/python3.7/site-packages/ReText/icontheme.py to icontheme.cpython-37.pyc
byte-compiling /home/$USER/.local/lib/python3.7/site-packages/ReText/converterprocess.py to converterprocess.cpython-37.pyc
byte-compiling /home/$USER/.local/lib/python3.7/site-packages/ReText/xsettings.py to xsettings.cpython-37.pyc
byte-compiling /home/$USER/.local/lib/python3.7/site-packages/ReText/webenginepreview.py to webenginepreview.cpython-37.pyc
byte-compiling /home/$USER/.local/lib/python3.7/site-packages/ReText/config.py to config.cpython-37.pyc
byte-compiling /home/$USER/.local/lib/python3.7/site-packages/ReText/syncscroll.py to syncscroll.cpython-37.pyc
byte-compiling /home/$USER/.local/lib/python3.7/site-packages/ReText/tabledialog.py to tabledialog.cpython-37.pyc
byte-compiling /home/$USER/.local/lib/python3.7/site-packages/ReText/tablemode.py to tablemode.cpython-37.pyc
byte-compiling /home/$USER/.local/lib/python3.7/site-packages/ReText/mdx_posmap.py to mdx_posmap.cpython-37.pyc
byte-compiling /home/$USER/.local/lib/python3.7/site-packages/ReText/preview.py to preview.cpython-37.pyc
byte-compiling /home/$USER/.local/lib/python3.7/site-packages/ReText/dialogs.py to dialogs.cpython-37.pyc
byte-compiling /home/$USER/.local/lib/python3.7/site-packages/ReText/tab.py to tab.cpython-37.pyc
byte-compiling /home/$USER/.local/lib/python3.7/site-packages/ReText/highlighter.py to highlighter.cpython-37.pyc
byte-compiling /home/$USER/.local/lib/python3.7/site-packages/ReText/editor.py to editor.cpython-37.pyc
running install_data
copying data/me.mitya57.ReText.desktop -> /home/$USER/.local/share/applications
copying icons/retext.svg -> /home/$USER/.local/share/icons/hicolor/scalable/apps
creating /home/$USER/.local/share/metainfo
copying data/me.mitya57.ReText.appdata.xml -> /home/$USER/.local/share/metainfo
creating /home/$USER/.local/share/retext
creating /home/$USER/.local/share/retext/icons
copying icons/retext.png -> /home/$USER/.local/share/retext/icons
copying icons/retext.svg -> /home/$USER/.local/share/retext/icons
creating /home/$USER/.local/share/retext/locale
running install_egg_info
running egg_info
creating ReText.egg-info
writing ReText.egg-info/PKG-INFO
writing dependency_links to ReText.egg-info/dependency_links.txt
writing entry points to ReText.egg-info/entry_points.txt
writing requirements to ReText.egg-info/requires.txt
writing top-level names to ReText.egg-info/top_level.txt
writing manifest file 'ReText.egg-info/SOURCES.txt'
reading manifest file 'ReText.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'retext_*.qm' under directory 'locale'
writing manifest file 'ReText.egg-info/SOURCES.txt'
Copying ReText.egg-info to /home/$USER/.local/lib/python3.7/site-packages/ReText-7.1.0.egg-info
running install_scripts
Installing retext script to /home/$USER/.local/bin
fixing Exec line in /home/$USER/.local/share/applications/me.mitya57.ReText.desktop
fixing Icon line in /home/$USER/.local/share/applications/me.mitya57.ReText.desktop
```

**Comment by mitya57** [comment]
There is no sign of failure here, it looks like it installed successfully. What exactly is wrong?

**Comment by sevku** [comment]
Okay I guess I lost patience while trying to install a markdown editor and none of them worked. I fixed it.

Details:

```
$ retext 
Traceback (most recent call last):
  File "/home/$USER/.local/bin/retext", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'docutils' distribution was not found and is required by ReText
```

then:
```
$ pip3 install docutils
Collecting docutils
  Downloading https://files.pythonhosted.org/packages/81/44/8a15e45ffa96e6cf82956dd8d7af9e666357e16b0d93b253903475ee947f/docutils-0.16-py2.py3-none-any.whl (548kB)
    100% |████████████████████████████████| 552kB 393kB/s 
retext 7.1.0 requires Markdown>=3.0, which is not installed.
retext 7.1.0 requires Markups>=2.0, which is not installed.
Installing collected packages: docutils
Successfully installed docutils-0.16

and then you'll have to install Markdown and Markups.

I think it should not be necessary to install this manually.
```

**Comment by mitya57** [comment]
Well, if you use `pip install` instead of the plain `setup.py install`, it will install all the dependencies.

Plain setuptools does not handle that, and this is not a bug in ReText.

**Comment by sevku** [comment]
I think this should be reopened until the manual dependencies have been fixed. Or maybe a new Issue should be created mentioning the missing dependencies.

**Comment by sevku** [comment]
Okay, I've written my last reply simultaneously to yours.

In that my suggestion: If pip install is the supposed method for installation, don't mention setup.py install at the top of your READMe, but instead have a section installation in your README where you mention pip install and maybe setup.py as a sidenote

**Comment by mitya57** [comment]
The dependencies are correctly specified here:

https://github.com/retext-project/retext/blob/d349f13addea6d2d6edb2e845b294c0667c5453f/setup.py#L139-L146

`pip install ReText` installs all of them.

**Comment by sevku** [comment]
see last comment that we've again written simultaneously

**Comment by mitya57** [comment]
Ok, I will update the README.

**Comment by sevku** [comment]
first impression is good btw, now that it works 👍
