### ISSUE TITLE
docutils is mandatory

### ISSUE THREAD

**Issue by matkoniecz** [retext-project/retext#562]
readme:

> ReText requires the following Python modules to run (pip will install them automatically):
>
>    PyQt5 (5.11 or later)
>    Markups (2.0 or later)
>
> We also recommend having these packages installed:
>
>    Markdown — for Markdown support
>    docutils — for reStructuredText support

command line:

> pkg_resources.DistributionNotFound: The 'docutils' distribution was not found and is required by ReText

```
Traceback (most recent call last):
  File "/home/mateusz/.local/bin/retext", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'docutils' distribution was not found and is required by ReText
```

installed from pip3 as recommended, Lubuntu 20.04

**Comment by mitya57** [comment]
I have updated the README. However, I do not understand how this could happen. Pip should have installed these dependencies. I have just tried to install ReText in a clean virtualenv and I get this:

```
$ pip install ReText
Collecting ReText
  Downloading ReText-7.2.1.tar.gz (522 kB)
     |████████████████████████████████| 522 kB 188 kB/s 
...
Collecting docutils
  Using cached docutils-0.17.1-py2.py3-none-any.whl (575 kB)
...
Successfully installed Markdown-3.3.4 Markups-3.1.1 PyQt5-5.15.4 PyQt5-Qt5-5.15.2 PyQt5-sip-12.9.0 Pygments-2.9.0 ReText-7.2.1 chardet-4.0.0 docutils-0.17.1 python-markdown-math-0.8
```

**Comment by matkoniecz** [comment]
No idea, for additional complexity I installed it with Ansible.
