### ISSUE TITLE
TypeError: arguments did not match any overloaded call:

### ISSUE THREAD

**Issue by sv-lary** [retext-project/retext#572]
```
$ retext markdown_sample.mkd 
QSocketNotifier: Can only be used with threads started with QThread
Using configuration file: /home/lary/.config/ReText project/ReText.conf
Traceback (most recent call last):
  File "/usr/bin/retext", line 33, in <module>
    sys.exit(load_entry_point('ReText==7.1.0', 'gui_scripts', 'retext')())
  File "/usr/lib/python3.10/site-packages/ReText/__main__.py", line 107, in main
    window = ReTextWindow()
  File "/usr/lib/python3.10/site-packages/ReText/window.py", line 60, in __init__
    self.move((int(screenRect.width()-self.width()))/2, (screenRect.height()-self.height())/2)
TypeError: arguments did not match any overloaded call:
  move(self, QPoint): argument 1 has unexpected type 'float'
  move(self, int, int): argument 1 has unexpected type 'float'
```
I replaced line 60 in /ReText/window.py

`self.move((screenRect.width()-self.width())/2, (screenRect.height()-self.height())/2)
`
to this one:

`self.move(int((screenRect.width()-self.width())/2), int((screenRect.height()-self.height())/2))
`

**Comment by mitya57** [comment]
This particular line was fixed in ReText 7.2.0, see commit 8b1d705b0ff3e5ef.

However if you use Python 3.10, you should use ReText ≥ 7.2.2, there is another important fix there.
