### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by WilliamLinxw** [retext-project/retext#611]
I tried `pip3 install ReText`, but it returns an error. The log is attached. Could you help me with it? Thank you! Running Ubuntu 20.04 with python 3.8

```
Collecting ReText
  Downloading ReText-8.0.0.tar.gz (492 kB)
     |████████████████████████████████| 492 kB 6.1 MB/s 
Collecting Markdown>=3.0
  Downloading Markdown-3.4.1-py3-none-any.whl (93 kB)
     |████████████████████████████████| 93 kB 1.4 MB/s 
Collecting Markups>=2.0
  Downloading Markups-3.1.3-py3-none-any.whl (12 kB)
Collecting PyQt6
  Downloading PyQt6-6.4.2.tar.gz (1.0 MB)
     |████████████████████████████████| 1.0 MB 48.3 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /tmp/tmperjrw0uh prepare_metadata_for_build_wheel /tmp/tmpxztfz_0c
         cwd: /tmp/pip-install-wkw3fmbh/PyQt6
    Complete output (26 lines):
    Querying qmake about your Qt installation...
    Traceback (most recent call last):
      File "/tmp/tmperjrw0uh", line 126, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/tmperjrw0uh", line 280, in <module>
        main()
      File "/tmp/tmperjrw0uh", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/tmp/tmperjrw0uh", line 130, in prepare_metadata_for_build_wheel
        return _get_wheel_metadata_from_wheel(backend, metadata_directory,
      File "/tmp/tmperjrw0uh", line 159, in _get_wheel_metadata_from_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/tmp/pip-build-env-gnbctw9v/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 46, in build_wheel
        project = AbstractProject.bootstrap('wheel',
      File "/tmp/pip-build-env-gnbctw9v/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/tmp/pip-build-env-gnbctw9v/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 601, in setup
        self.update(tool)
      File "/tmp/pip-install-wkw3fmbh/PyQt6/project.py", line 162, in update
        raise UserException(
    sipbuild.exceptions.UserException
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmperjrw0uh prepare_metadata_for_build_wheel /tmp/tmpxztfz_0c Check the logs for full command output.
```

**Comment by mitya57** [comment]
pip failed when installing PyQt6, not ReText.

And it failed because it did not find the pre-built wheel on PyPI, tried to compile it from source, but found qmake from Qt 5 instead of Qt 6.

Try to install a newer pip first (`pip3 install --upgrade pip`). Maybe it will help.

**Comment by gloghry** [comment]
I had this same issue today and updating pip3 didn't fix it. Seems PyQt6 cannot be installed using `pip3` for some reason, and the documentation for PyQt6 says to install using just `pip` [seen here](https://pypi.org/project/PyQt6/)

I downloaded PyQt6 using `pip install PyQt6` and then installing Retext went fine
