### ISSUE TITLE
[Flatpak] ReText freezes when attempting font change (both editor and preview)

### ISSUE THREAD

**Issue by lucknaumann** [retext-project/retext#639]
Hi. I posted at the other [repo](https://github.com/flathub/me.mitya57.ReText/issues/7), but it occurred to me that maybe I'm supposed to post here instead. Apologies if that's not the case.

As the title says, the program freezes when attempting a font change  with both the editor and the preview.
The second either font dialog pops up, the program freezes and needs to be terminated, regardless of launching from the terminal or from the standard application launcher.
This doesn't happen with the Ubuntu repository version or the python version.

Console output (the first part prior to `^C` is the initial launch, the rest is after it froze - probably obvious)

```bash
$ flatpak run me.mitya57.ReText
Qt: Session management error: Could not open network socket
Using configuration file: /home/<username>/.var/app/me.mitya57.ReText/config/ReText project/ReText.conf
libva error: /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/iHD_drv_video.so init failed
^C
[2:24:0327/094033.879528:FATAL:bus.cc(1226)] D-Bus connection was disconnected. Aborting.
$ Process Process-1:
Traceback (most recent call last):
File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/app/lib/python3.11/site-packages/ReText/converterprocess.py", line 72, in _converter_process_func
job = receiveObject(conn_child)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/lib/python3.11/site-packages/ReText/converterprocess.py", line 41, in receiveObject
sizeBuf = recvall(sock, 4)
^^^^^^^^^^^^^^^^
File "/app/lib/python3.11/site-packages/ReText/converterprocess.py", line 34, in recvall
raise EOFError('Received 0 bytes from socket while more bytes were expected. Did the sender process exit unexpectedly?')
EOFError: Received 0 bytes from socket while more bytes were expected. Did the sender process exit unexpectedly?
^C

```

Operating System: KDE neon 5.27 (Ubuntu 22.04 / Jammy)
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.114.0
Qt Version: 5.15.12
Kernel Version: 6.2.0-39-generic (64-bit)
Graphics Platform: X11

**Comment by lucknaumann** [comment]
Closing as the other repo was the correct place.
